### ISSUE TITLE
Non completely fit in area

### ISSUE THREAD

**Issue by fracz** [cemulate/polyomino-solver#2]
Can I use the software to find a "any fit" solution somehow? I.e. I'm not looking for exact fit into the canvas, but any fit that will be capable of holding all of given shapes.

For example: 

Shapes
```
TTT
 T

ZZ
 ZZ
```

Fit into 2x5 canvas:

```
 TZZ
TTTZZ
```

Currently, it says that there is no solution :-(

**Comment by cemulate** [comment]
Nothing like closing a three year old issue but,

This is because "Algorithm X (Dancing Links)" solver only finds exact solutions; to find partial or inexact solutions you will need to use one of the SAT solver options. I've documented/noted this in the UI.
