### ISSUE TITLE
Doesn't work for even the simplest puzzles in Sigils of Elohim

### ISSUE THREAD

**Issue by sarimmehdi** [cemulate/polyomino-solver#6]
I tried using your solver for the puzzles in Sigils of Elohim but it says no solution even for the simplest puzzle

**Comment by cemulate** [comment]
Can you elaborate, with a screenshot? The app certainly works; if there is a UX issue that's confusing perhaps it can be addressed if I know your issue.

**Comment by sarimmehdi** [comment]
[Puzzle Solution - Easy 1-8](https://steamcommunity.com/sharedfiles/filedetails/?id=327117676):

![github](https://user-images.githubusercontent.com/36595832/193482958-48f8d792-96a7-452a-85b0-8c0e0c908a66.PNG)

**Comment by cemulate** [comment]
You need to draw/paint in the region that the polyominos are to be fit into in the gray rectangle on the right, as instructed in the UI:
> Draw (color in) the region to fit the polyominos into

![image](https://user-images.githubusercontent.com/342497/193484272-ff944df4-ab9a-41b9-97a5-1038b9aacca3.png)

In this case it is a 4x4 rectangle but it can accommodate arbitrary destination shapes.
