### ISSUE TITLE
Cells in the preview of the selected polyominos are sized inconsistently

### ISSUE THREAD

**Issue by justfortherec** [cemulate/polyomino-solver#7]
I created custom polyominos as pictured in the screenshot:

![image](https://user-images.githubusercontent.com/935534/194701728-43d5a43f-6c6f-4585-896b-6e696e5a06f9.png)

In the preview, all pieces are shown with a fixed size (50×50 pixels).
This causes the cells of the different pieces to have inconsistent size, if the sides of the polyominos are different length.

I'd find it (a) better looking and (b) more helpful for the topic at hand, if the cell size of all polyominos was the same.

That could be achieved in CSS by giving the elements with class `cell` a fixed size instead of the `polyomino-control` elements that are currently sized 50×50.

**Comment by cemulate** [comment]
Resolved in the recent UX refresh f931f4d7abe03da811f2107c2ae02f9a70d98991
